theme: minima
title: Nanotechnology
author: Anupama Subramanian
email: anupama0699@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Ultimate place to be to know about the recent developments in the field of Nanotechnology!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
